// -----// AUTH_BY_GOOGLE //-----//
export const AUTH_BY_GOOGLE_STARTED = 'AUTH_BY_GOOGLE_STARTED';
export const AUTH_BY_GOOGLE_SUCCESS = 'AUTH_BY_GOOGLE_SUCCESS';
export const AUTH_BY_GOOGLE_FAILURE = 'AUTH_BY_GOOGLE_FAILURE';
// -----// AUTH_LOGIN //-----//
export const AUTH_LOGIN_STARTED = 'AUTH_LOGIN_STARTED ';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS ';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE ';
// -----// AUTH_REGISTER //-----//
export const AUTH_REGISTER_STARTED = 'AUTH_REGISTER_STARTED';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
