// -----// AUTH //-----//

// --- // AUTH_BY_GOOGLE // --- //
export const AUTH_BY_GOOGLE_STARTED = 'AUTH_BY_GOOGLE_STARTED';
export const AUTH_BY_GOOGLE_SUCCESS = 'AUTH_BY_GOOGLE_SUCCESS';
export const AUTH_BY_GOOGLE_FAILURE = 'AUTH_BY_GOOGLE_FAILURE';

// --- // AUTH_LOGIN // --- //
export const AUTH_LOGIN_STARTED = 'AUTH_LOGIN_STARTED ';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS ';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE ';

// --- // AUTH_REGISTER // --- //
export const AUTH_REGISTER_STARTED = 'AUTH_REGISTER_STARTED';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

// -----// AUTH_LOGOUT //-----//
export const AUTH_LOGOUT_STARTED = 'AUTH_LOGOUT_STARTED';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

// -----// INIT_KAPUSTA //-----//

// --- // INIT_KAPUSTA // --- //
export const INIT_KAPUSTA_STARTED = 'INIT_KAPUSTA_STARTED';
export const INIT_KAPUSTA_SUCCESS = 'INIT_KAPUSTA_SUCCESS';
export const INIT_KAPUSTA_FAILURE = 'INIT_KAPUSTA_FAILURE';

// -----// BALANCE //-----//

// --- // GET_BALANCE // --- //
export const GET_BALANCE_STARTED = 'GET_BALANCE_STARTED';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';

// --- // POST_BALANCE // --- //
export const POST_BALANCE_STARTED = 'POST_BALANCE_STARTED';
export const POST_BALANCE_SUCCESS = 'POST_BALANCE_SUCCESS';
export const POST_BALANCE_FAILURE = 'POST_BALANCE_FAILURE';

// -----// INCOME //-----//

// --- // GET_INCOME // --- //
export const GET_INCOME_STARTED = 'GET_INCOME_STARTED';
export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS';
export const GET_INCOME_FAILURE = 'GET_INCOME_FAILURE';

// --- // POST_INCOME // --- //
export const POST_INCOME_STARTED = 'POST_INCOME_STARTED';
export const POST_INCOME_SUCCESS = 'POST_INCOME_SUCCESS';
export const POST_INCOME_FAILURE = 'POST_INCOME_FAILURE';

// --- // DELETE_INCOME // --- //
export const DELETE_INCOME_STARTED = 'DELETE_INCOME_STARTED';
export const DELETE_INCOME_SUCCESS = 'DELETE_INCOME_SUCCESS';
export const DELETE_INCOME_FAILURE = 'DELETE_INCOME_FAILURE';

// -----// PRODUCTS //-----//

// --- // GET_PRODUCTS // --- //
export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

// --- // POST_PRODUCTS // --- //
export const POST_PRODUCTS_STARTED = 'POST_PRODUCTS_STARTED';
export const POST_PRODUCTS_SUCCESS = 'POST_PRODUCTS_SUCCESS';
export const POST_PRODUCTS_FAILURE = 'POST_PRODUCTS_FAILURE';

// --- // DELETE_PRODUCTS // --- //
export const DELETE_PRODUCTS_STARTED = 'DELETE_PRODUCTS_STARTED';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_FAILURE = 'DELETE_PRODUCTS_FAILURE';

// -----// COSTS //-----//

// --- // GET_COSTS // --- //
export const GET_COSTS_STARTED = 'GET_COSTS_STARTED';
export const GET_COSTS_SUCCESS = 'GET_COSTS_SUCCESS';
export const GET_COSTS_FAILURE = 'GET_COSTS_FAILURE';

// --- // POST_COSTS // --- //
export const POST_COSTS_STARTED = 'POST_COSTS_STARTED';
export const POST_COSTS_SUCCESS = 'POST_COSTS_SUCCESS';
export const POST_COSTS_FAILURE = 'POST_COSTS_FAILURE';

// --- // DELETE_COSTS // --- //
export const DELETE_COSTS_STARTED = 'DELETE_COSTS_STARTED';
export const DELETE_COSTS_SUCCESS = 'DELETE_COSTS_SUCCESS';
export const DELETE_COSTS_FAILURE = 'DELETE_COSTS_FAILURE';

// -----// TRANSACTIONS //-----//

// --- // GET_TRANSACTIONS // --- //
export const GET_TRANSACTIONS_STARTED = 'GET_TRANSACTIONS_STARTED';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';

// -----// APP //-----//

// --- // SET_PERIOD // --- //
export const SET_PERIOD = 'SET_PERIOD';
